apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ndc-scheduler.fullname" . }} 
  labels:
    {{- include "ndc-scheduler.labels" . | nindent 4 }} 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ndc-scheduler.selectorLabels" . | nindent 6 }} 
  template:
    metadata:
      labels:
        {{- include "ndc-scheduler.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }} 
          image: "{{ .Values.image }}" 
          imagePullPolicy: {{ .Values.imageConfig.pullPolicy }}
          ports:
          - containerPort: 8080
